name: Swift Package Tests

on:
  push:
    branches:
      - main
    paths:
      - 'Sources/**'
      - 'Tests/**'
      - '.github/workflows/test.yml'
  pull_request:
    paths:
      - 'Sources/**'
      - 'Tests/**'
      - '.github/workflows/test.yml'
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest
    env:
      GDTF_SHARE_PASSWORD: ${{ secrets.GDTF_SHARE_PASSWORD }}

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Select Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      # Restore cached Fixtures folder
      - name: Restore Fixtures cache
        uses: actions/cache@v3
        with:
            path: .cache/Fixtures/
            key: ${{ runner.os }}-fixtures
            restore-keys: |
                ${{ runner.os }}-fixtures

      # Run tests
      - name: Run Swift tests
        run: swift test

      # Save updated Fixtures folder to cache
      - name: Save Fixtures cache
        uses: actions/cache@v3
        with:
            path: .cache/Fixtures/
            key: ${{ runner.os }}-fixtures
